### ISSUE TITLE
Spawned proxies use local allocator as bootstrap?

### ISSUE THREAD

**Issue by t-lin** [Multi-Tier-Cloud/service-manager#32]
This would need a new way to pass the bootstrap address to the proxy.
Allocators can then pass its own listening address.
- An open question is, if they should listen to a well-known port, or leave it as an ephemeral port?

**Comment by mwyzhao** [comment]
In the well-known port case, the only con I can think of would probably if there is a port conflict.

In the ephemeral port case, we'll need to find a way to fetch the listening addresses from the libp2p node, though I think it's already being done to print it out to terminal.

Overall I think it's probably fine to leave it ephemeral (?)
We could support both and make it an option easily enough.

**Comment by t-lin** [comment]
Yeah, I'm leaning towards supporting it as an option. Ephemeral would be more "secure" (i.e. prevents potential DoS attacks on the allocator, if people know its port). On the other hand, if the allocator restarts, it'll choose a new port number (but the hope is by that time, the proxies already running would have discovered and connected to other nodes). Though, then what if the containers restart (e.g. the machine reboots)... 🤔

**Comment by mwyzhao** [comment]
If we support both then that's a problem that we'll need to deal with anyway. One option could be to fall back onto the monitoring nodes as central bootstraps in that case. Another option is to provide a route for an allocator to update the bootstraps environment variable passed into the containers to point to itself for all existing containers that would be done on allocator startup. I think both of these together would be the most robust.

**Comment by t-lin** [comment]
> One option could be to fall back onto the monitoring nodes as central bootstraps in that case. 

That's definitely doable. The new `-bootstrap` flag allows multiple invocations to specify multiple bootstraps. We previously discussed the possibility of creating a new environment variable that'll be passed to the container. We can populate this environment variable with the bootstrap flags + values.

For example: an environment variable `PROXY_OPTIONS`, which will consist of one or more `-bootstrap <multiaddr>` values, and any other flags we want to pass (e.g. psk?). Then the Dockerfile's `CMD` line can be updated to call `./proxy $PROXY_OPTIONS 4200 ...`

@hivanco
