### ISSUE TITLE
Use a Hash Cache in Proxy

### ISSUE THREAD

**Issue by t-lin** [Multi-Tier-Cloud/service-manager#41]
For performance evaluations later, we'd like to see the overhead of the proxy / P2P service.

A preliminary performance benchmark (with peer already stored in `pcache`), `proxy`, client, and `hash-lookup` service all within the same host, and target service running in a separate host, and using TCP keep-alives:
```
Requests per second:    341.70 [#/sec] (mean)
Time per request:       2.927 [ms] (mean)
Time per request:       2.927 [ms] (mean, across all concurrent requests)
Transfer rate:          51.39 [Kbytes/sec] received
```

Compared against direct client to service through the underlying network:
```
Requests per second:    4357.54 [#/sec] (mean)
Time per request:       0.229 [ms] (mean)
Time per request:       0.229 [ms] (mean, across all concurrent requests)
Transfer rate:          655.33 [Kbytes/sec] received
```

While some overhead is obviously expected, it should be possible to improve upon these results. One clear bottlenecks I've noticed is the need to do a hash lookup request each time. Ideally it should cache results for some time to avoid constantly querying the lookup service.

**Comment by hivanco** [comment]
Proxy now queries RegistryCache to get ServiceInfo. If does not exist or expired, then it sends request to registry-service.
Can specify TTL in seconds with the `--rcache-ttl` flag.
Future consideration: pre-fetch entries that have been requested multiple times.

**Comment by t-lin** [comment]
Thanks! Will test out soon.
