### ISSUE TITLE
Refactor LCA constructor to advertise after node creation

### ISSUE THREAD

**Issue by t-lin** [Multi-Tier-Cloud/service-manager#43]
Current calls to `NewLCAManager()` involves creating a Node twice: https://github.com/Multi-Tier-Cloud/service-manager/blob/4f347a5116f10b0edcae34f44b64c723edd80cf1/lca/lca-manager.go#L245

Utilize new function to reduce Node creation to once:
https://github.com/Multi-Tier-Cloud/common/blob/ad8b0aa9539f2a1008aa9f9c530510e75a460ebf/p2pnode/p2pnode.go#L81

**Comment by t-lin** [comment]
@michaelweiyuzhao Hold off on this for a bit.

I'm thinking of changing the startup params of `proxy` to pass the actual rendezvous hash directly on the CLI (rather than the human-readable name), so it doesn't have to do the extra query to the hash lookup service. This would also prevent old versions of services from being accidentally queried when we update the hash in the hash-lookup service. Let me know if you have any opposition to this idea.

**Comment by mwyzhao** [comment]
In that case how would the user get the hash, I guess through hl-cli? I thought the point of having human readable names was to make things easier on the users. If we get hash caching, which can have a long TTL because realistically people probably aren't going to go around changing the names of their services often and the hash is based on the service name, this would only save the few seconds during startup that it would need to query hash-lookup wouldn't it.

**Comment by t-lin** [comment]
Sorry, I should've mentioned this is for when the `proxy` operates in service mode (i.e. within a container), so this would apply for the `SERVICE` parameter after the options:
```
$ ./proxy [OPTIONS ...] PORT [SERVICE] [ADDRESS]
```
The `allocator` should be able to provide this directly since it already has that info.

If running the proxy in service mode outside a container (e.g. for debugging purposes), I guess yeah, they'd use the CLI to first find the service hash, then run it.

**Comment by mwyzhao** [comment]
I guess what I'm saying is, I don't see why it would be needed other than to speed up booting up a proxy. We can just cache the hash-lookup results on startup and use it for the rest of the run. After the initial setup, everything would run the same as if it was provided by command line.

For running it through allocator maybe the few seconds saved is what we want, but for debugging and running manually I think the ability to provide the service name in a human-readable format is still valuable.

By the way I'm not opposed to the idea, I just don't know if it's a good idea to scrap the human-readable name for booting altogether.

**Comment by t-lin** [comment]
Speed is definitely one of the reasons. The case where a rebooted container responds if the lookup entry was modified is another concern. Right now the `hash-lookup` service allows anyone to change the hash entry corresponding to the human-readable name (and there's no versioning info).

What if we simultaneously support both human-readable and hash formats? Kinda like how git supports using commit hashes and branch names in its various commands (checkout, merge, etc.). I'm not sure how it does it, either it uses regex to determine the format, or it checks them in some order.

**Comment by mwyzhao** [comment]
I see, in that case I think an easy way to support it is just to make two flags and make the hash override the name if both are provided or something like that.

**Comment by t-lin** [comment]
That could work as well. If using flags, maybe a simple boolean flag to toggle hash vs human-readable.
